### ISSUE TITLE
Obsolete manual instructions

### ISSUE THREAD

**Issue by HorstSteuer** [ANR-COMPASS/shesha#13]
The manual seems not to be up to date with regard to the Generic Controller. It states in the section 'Generic Controller':
>  Use the command sim.rtc.set_commandlaw(0,b"2matrices") to switch to the “2matrices” mode.

sim.rtc does not have a set_commandlaw any longer. Instead, aoSupervisor has the method setIntegratorLaw but no equivalent for the 2matrices (or 'E matrix') mode. I guess one would have to set 
`supervisor.rtc.d_control[nControl].set_commandlaw("2matrices")` ? 

This issue is currently not important for me as I don't really need the 2 matrices mode. i just stumbled upon this when looking at the generic controller using the integrator.

**Comment by a-sevin** [comment]
You right, need to update the documentation

**Comment by floferreira** [comment]
Yes, I will edit the title of this issue to be more general, and I let it open until I find time to update the documentation
