### ISSUE TITLE
Generic controller ignores gain from parameter file

### ISSUE THREAD

**Issue by HorstSteuer** [ANR-COMPASS/shesha#14]
When using a generic controller (integrator mode), the gain attribute of the controller is not set as a scalar. Looking at the method init_controller_generic in rtc_init.py, the parameter is only used to create and set a vector mgain, but mgain is not applicable in the integrator mode. Since the gain then is 0, the simulation results in Strehl values just slightly above 0, no matter the Cmat set.

I believe  this issue could be fixed by adding the following line:
`rtc.d_control[i].set_gain(p_controller.gain)`

**Comment by a-sevin** [comment]
Agree

**Comment by floferreira** [comment]
Hi Horst,

It's more a feature than a bug in fact : when the user chooses to use a generic controller, he chooses to have a fully configurable controller which comes with default parameters that are "safe" from an AO RTC point of view, i.e. command matrix full of zeros and gain equals to zero also.
Our philosophy is to suppose that user who want to use a generic controller will write its own script where he will set those parameters, independently of what is written in the parfile.
But I should probably document this point, I agree....

**Comment by HorstSteuer** [comment]
Okay, I guess what confused me was the following snippet in `init_controller_generic`, which indeed uses the parameter to create and set the mgain matrix of the generic controller (for the (obsolete?) 2matrices mode?) :
```
mgain = np.ones(size, dtype=np.float32) * p_controller.gain
rtc.d_control[i].set_mgain(mgain)
```
