### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by Tomeu7** [ANR-COMPASS/shesha#17]
Dear researchers,

When I try to execute the test:

```
ipython -i shesha/scripts/closed_loop.py data/par/par4bench/scao_sh_16x16_8pix.py
```

The following error occurs:

```
TypeError: add_controller(): incompatible function arguments. The following argument types are supported:
    1. (self: sutraWrap.Rtc_FFF, context: carmaWrap.context, nvalid: int, nslope: int, nactu: int, delay: float, device: int, typec: str, dms: sutraWrap.Dms=None, idx_dms: numpy.ndarray[int32]=[], ndm: int=0, idx_centro: numpy.ndarray[int32]=[], ncentro: int=0, Nphi: int=0, wfs_direction: bool=False) -> int
    2. (self: sutraWrap.Rtc_FFF, context: carmaWrap.context, nvalid: int, nslope: int, nactu: int, delay: float, device: int, typec: str) -> None

Invoked with: <sutraWrap.Rtc_FFF object at 0x7fa9ae91b1f0>, <carmaWrap.context object at 0x7fa9fc18ad70>, 184, 368, 222, 1.0, 0, 'ls', <sutraWrap.Dms object at 0x7fa9fc098bb0>, array([0, 1], dtype=int32), 2, array([0], dtype=int32), 1, -1, False, 0
```
What I think it happens is that add_controller is invoked with an additional argument that should not be there. If I modify rtc_init in line 389 deleting p_controller.nstates I get the following result.

```
----------------------------------------------------
iter# | S.E. SR | L.E. SR | ETR (s) | Framerate (Hz)
----------------------------------------------------
100 	 0.742 	  0.694	     6.2 	 144.6
200 	 0.758 	  0.719	     5.5 	 145.3
300 	 0.752 	  0.722	     4.8 	 145.0
400 	 0.718 	  0.720	     4.1 	 144.9
500 	 0.763 	  0.721	     3.5 	 145.0
600 	 0.767 	  0.722	     2.8 	 145.8
700 	 0.738 	  0.723	     2.1 	 145.8
800 	 0.739 	  0.721	     1.4 	 145.4
900 	 0.752 	  0.721	     0.7 	 145.5
1000 	 0.749 	  0.723	     0.0 	 146.7
 loop execution time: 6.881890535354614   ( 1000 iterations),  0.006881890535354615 (mean)   145.3089081935639 Hz
```

I have installed COMPASS following the instructions found in https://anr-compass.github.io/compass/install.html with cuda 10.0.326 using the command conda install -c compass/label/cuda100 compass -y. My current gpu is nvidia geforce 940MX (which is not very powerful).

I just want to know if everything correct so I can start using the program.

Thanks in advance.

**Comment by a-sevin** [comment]
Hi,

It's a problem with invalid version between compass binaries and shesha module (need to raise an error to handle that)

The first solution is to downgrade shesha to v4.3.0 but there is a bug with old cards in this version.
I will provide new binaries for 10.0 soon.

Keep you inform,

Arnaud

**Comment by a-sevin** [comment]
Could you try to update compass binaries?
```conda install -c compass/label/cuda100 compass -y```

Arnaud

**Comment by Tomeu7** [comment]
Thanks, now it works without changing that line.

I'll test the code and inform you of any bug I find.

**Comment by Coolnesss** [comment]
Hey, I am getting the same error when installing with

`conda install -c compass/label/cuda101 compass -y`

Did you fix the binary for cuda 10.1 also?

**Comment by floferreira** [comment]
Hi,

If you have the problem, probably not... 
By the way, we are currently preparing a new release of compass (v5.0) which will bring a lot of changes in shesha. The problem will be solved with this release

**Comment by a-sevin** [comment]
Hi, 

It's not normal, do you have the same version of compass and shesha ?
Do know it, could you do that and send us the output :

- #>  ```conda list | grep ^compass```
- #> ```cd $SHESHA_ROOT; git log --oneline -1```

Thanks

**Comment by Coolnesss** [comment]
Hello, thanks for the quick reply! Here is the information
```
$ conda list | grep ^compass
compass                   4.3.1                   cuda101    compass/label/cuda101
$ git log --oneline -1
a0843ce (HEAD -> master, tag: v4.4.1, origin/master, origin/beta, origin/HEAD) Release v4.4.1:
```

**Comment by a-sevin** [comment]
Try to update compass : conda install -c compass/label/cuda101 compass -y

you should be on compass-4.4.1-cuda101 (the same of shesha)

**Comment by Coolnesss** [comment]
Hey, thanks! For me, anaconda was installing the old version by default. I had to specify the version 4.4.1 by doing
`conda install -c compass/label/cuda101 compass=4.4.1 -y`
 and after that it worked. Thanks for your help.
