### ISSUE TITLE
Aperture Type -> string decode leads to AttributeError

### ISSUE THREAD

**Issue by HorstSteuer** [ANR-COMPASS/shesha#18]
In make_pupil.py there are a couple occurrences of:
`tel.type_ap.decode('UTF-8')`

`tel.type_ap` resolves to a `<class 'str'>` which leads the above to fail since in Python 3 str doesn't have a decode method.

When using EELT_NOMINAL as aperture type (p_tel.set_type_ap("EELT_NOMINAL"), the error reported is `AttributeError: 'str' object has no attribute 'decode'`

I believe this could be solved by simply removing all `.decode('UTF-8')` in make_pupil.py.

**Comment by a-sevin** [comment]
Hi Host,

Happy to read you again ! String vs Byte was a nightmare with Cython. I think it's a legacy code of our previous Cython binding (before switching to pybind11).

Need to see the impact with the current architecture.

Thanks to propose a fix.

**Comment by HorstSteuer** [comment]
Has been fixed in the latest version (v.5.0).
