### ISSUE TITLE
How to use shesha as a module

### ISSUE THREAD

**Issue by Coolnesss** [ANR-COMPASS/shesha#19]
I followed the installation instructions and am able to run the scripts in the `scripts` folder of this repo. However, I would like to use version control for my own code as well so it is not practical to put code in the scripts folder of a repo that is not mine. 

I tried cloning shesha as a git submodule into my project. I have a `test.py` file with the contents 

`import shesha`

If I try to run it, I get 
```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import shesha
  File "/home/chang/test/shesha/__init__.py", line 1, in <module>
    import shesha_ao as shao
ModuleNotFoundError: No module named 'shesha_ao'
```
Is there a way to use shesha from outside of the git respository itself?

**Comment by a-sevin** [comment]
Hi Chang,

I'm sorry but where you find your `shesha/__init__.py`, those lines does not correspond to the `shesha/__init__.py` in the [repo](https://github.com/ANR-COMPASS/shesha/blob/master/shesha/__init__.py)... shesha_ao corresponds to a very very old module which is no longer used.

Best,

Arnaud

**Comment by Coolnesss** [comment]
Hey, thanks for your help.

The file that is getting run when importing is [this one](https://github.com/ANR-COMPASS/shesha/blob/master/__init__.py). I removed that file and the problem is solved. I guess if it is old, it can be removed from the repo?

**Comment by a-sevin** [comment]
Sure ! Thanks, we will remove it
