### ISSUE TITLE
voltage vector to visual presentation

### ISSUE THREAD

**Issue by jnousi** [ANR-COMPASS/shesha#21]
Hi,

I'm working with the "scao_sh_40x40_8pix.py" simulation and I'd like to have my data and commands as 2-d images. I managed to convert the slopes  ( "getSlope()" ) to two 40x40 images with 1200 measurements each, but I'm struggling to do the same for control voltages ("setCommand()", "getCommand()" ).  

Is there an easy way to convert command vector to 41x41 image with 1286 commands i.e. to find out the active actuators in this grid? I guess we are having a square grid.

best,
Jalo

**Comment by floferreira** [comment]
Hi Jalo,

This king of grid for valid actuators is not available in COMPASS, as we do not need it directly...

However, you can easily retrieve it from actuators positions in the pupil (supervisor.config.p_dms[n]._xpos, supervisor.config.p_dms[n]._ypos), knowing also the DM pitch stored in supervisor.config.p_dms[n]._pitch.

For example, this sample should do the job : 
```python
xvalid = supervisor.config.p_dm0._xpos
yvalid = supervisor.config.p_dm0._ypos
xvalid = ((xvalid - xvalid.min()) / supervisor.config.p_dm0._pitch).astype(np.int)
yvalid = ((yvalid - yvalid.min()) / supervisor.config.p_dm0._pitch).astype(np.int)
valid_actus = np.zeros((supervisor.config.p_dm0.nact, supervisor.config.p_dm0.nact))
valid_actus[xvalid, yvalid] = 1 # or your_command_vector
```

Cheers,
Florian

**Comment by jnousi** [comment]
Thanks Florian!
