### ISSUE TITLE
Installation issue with conflicting python packages

### ISSUE THREAD

**Issue by 30503523** [ANR-COMPASS/shesha#22]
Hi All,

I'm having an install issue with conflicting python packages when importing the COMPASS package. 

I'm using this command from the instructions:
_**conda install -c compass compass -y**_

This results in several attempts to deal with conflicts and takes some time before the import fails:
_Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for sphinxcontrib-websupport ujson qdarkstyle wcwidth imageio sphinxcontrib rtree simplegeneric pathlib2 decorator_

I've tried cleaning out the packages from python but there still seems to be an issue.
Let me know if there is an easy fix - I feel like I'm doing something wrong in the python / conda set up.

Thanks,

Jeffrey

**Comment by 30503523** [comment]
I've resolved my own issue - I was using Anaconda 2020.02 as I have used Anaconda before. 

Removed and installed Miniconda3 as suggested by the instruction manual. There were three conflicts importing compass that resolved fine.

Regards,

Jeffrey

**Comment by a-sevin** [comment]
Thank you, I close this issue
