### ISSUE TITLE
KL basis on a single "pzt"

### ISSUE THREAD

**Issue by jnousi** [ANR-COMPASS/shesha#34]
Hi,

I'm trying to get a 40x40 shs scao system with a single "pzt" mirror under control in KL basis. I'm using using the following methods, but with no success. (always something crazy happening in the control loop) 

M2V, _  = self.supervisor.basis.compute_modes_to_volts_basis("KL2V")
M2S      = self.supervisor.calibration.do_imat_modal(0, kl_push, M2V)

I wonder if you have some kind of example code to do this right and if you'd like share it. 

the best and many thanks,
Jalo

**Comment by floferreira** [comment]
Hi Jalo,

Here a sample code of how we do this:
```python
M2V,_ = self.supervisor.basis.compute_modes_to_volts_basis("KL2V")
import shesha.ao.basis as bas
cmatKL = bas.compute_cmat_with_KL(supervisor.rtc._rtc, M2V, number_of_modes_you_want_to_filter)
```
At this point, the new command matrix cmatKL is already uploaded, so you can start your loop.

I agree that it is not trivial with the current API: we should add those "compute_cmat" modal method to the modalBasis optimizer to make it easily accessible...

Let us know if this sample solved your issue: in any case, we will let this issue open until we make those methods available in the optimizer.

Thank you for your feedback,
Florian

**Comment by jnousi** [comment]
Thanks Florian,

It's seems to be working now. I also tried this before but had a small bug in my code and ended up having trouble. Knowing the robust way to do this really helped. 

- Jalo

**Comment by jnousi** [comment]
I'm getting good results by controlling the system with KL-based cmat, and everything seemed fine. However, when I tried to analyze individual modes, I noticed the  "M2V" matrix looked strange (at least in the actuator space). It repeats some modes, the conditioning number is big, and it is not orthogonal. 

I'm a bit puzzled since everything seems fine in the end-to-end simulations. Do you think there's a logical explanation? The KL basis si called from COMPASS, and I cannot see the calculations.

Best and many thanks,
Jalo
