### ISSUE TITLE
cured controller gives bad results for provided parameter file

### ISSUE THREAD

**Issue by sraffetseder** [ANR-COMPASS/shesha#41]
Hi,
for the parameter file
`/data/par/par4tests/test_sh_cured.py`
at least on my machine strehl is close to 0, after 1000ts.

Using 16x16 subapertures instead of 8x8 (as `simul_name = "bench_scao_sh_16x16_8pix"` suggests) results in reasonable strehl, for whatever reason.

You might change the number of subapertues: `p_wfs0.set_nxsub(16)`

Thanks, Stefan

**Comment by a-sevin** [comment]
Dear Stefan,

Thank you for the fix, it will be released with the next version of shesha.

Cheers,

Arnaud
