### ISSUE TITLE
Wrong PYTHONPATH in README?

### ISSUE THREAD

**Issue by greensquirrel** [ANR-COMPASS/shesha#6]
I had to fix shesha part in PYTHONPATH in order to run the widget_ao.py GUI `ipython -i shesha/widgets/widget_ao.p`

Thus:
s|export PYTHONPATH=$SHESHA_ROOT/src:$PYTHONPATH|export PYTHONPATH=$SHESHA_ROOT:$PYTHONPATH

Can you update the README?

**Comment by floferreira** [comment]
Done
Thank you for the feedback !
