### ISSUE TITLE
K-L DM error?

### ISSUE THREAD

**Issue by GillesOrban** [ANR-COMPASS/shesha#7]
Hello,

I have been experimenting with K-L DM and I have noticed a potential issue in the K-L DM shape generation.

A simple way to illustrate it is to run the example:
`par4test/test_sh_kl.py`
and then look at the target phase, e.g. 
`plt.imshow(supervisor.getTarPhase(0))`
Last two rows and columns are uncorrected (some of those pixels will be within the pupil and thus may have a detrimental effect).

The K-L phase generation seems to be buried in the COMPASS architecture (as far as I understand), so it is difficult to pinpoint the problem.
Nevertheless, I have been looking at `kl_util.py` and found that the modes in cartesian coordinates (`cdxy`) have a downsized aperture due to the interpolation in the function `pol2car`. But `pol2car` does not seem to be called in the COMPASS simulation, so it is only an hypothesis.

Hope this make senses.
Best regards,

Gilles

**Comment by floferreira** [comment]
Hi,

Thank you for reporting this bug, it totally makes sense indeed...
This bug will be corrected in the next release, coming very soon.
Until this release, you can correct this bug by commenting lines 105 to 107 in the file shesha/init/target_init.py : 

               if (dm[k].type == scons.DmType.KL):
                    xoff += 2
                    yoff += 2

Comment those lines, and everything should work fine.

Again, thank you for your feedback on this : it helps us improving the platform.

Best regards,
Florian Ferreira
